spring:
  application:
    name: ps5GameTradingSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ps5game?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=Asia/Shanghai
mybatis-plus:
    # 配置类型别名包扫描路径
    type-aliases-package: com.zxy.ps5gametradingsystem.entity
    # 配置mapper.xml文件位置（重要！）
    mapper-locations: classpath*:/mapper/**/*.xml
server:
  servlet:
    context-path: /game
  port: 7777
